### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by pablitoc**
@pjkelly Almost ready for review... lol Let me know if I am missing anything

### CODE REVIEW

**Comment by pjkelly** [comment]
A few revisions and a question:
- [ ] Update README so it doesn't say it depends on a `deploy` user.
- [ ] Update README to show installation of a specific version via galaxy.
- [ ] Remove commented shell commands from tasks.

Having the following variables feels dirty to me - I know we're doing it because of the inconsistent naming of files and shell output on Ruby's end, but I can't help but thing there's gotta be a cleaner way.

``` yaml
  mversion: 2.0
  fversion: 2.0.0-p576
  cversion: 2.0.0p576
```

I'm also interested to know what these variable looks like in newer Ruby versions where the patch numbers don't exist anymore, do you end up with something like this?

``` yaml
  mversion: 2.1.2
  fversion: 2.1.2
  cversion: 2.1.2
```

**Comment by pjkelly** [comment]
Here's one alternative approach that simplifies the variables a bit:

https://github.com/chelsea/ansible-example-ruby/tree/master/roles/webserver

Thats kind of nice too because it gives you to option to pull the files down from somewhere other than Ruby's FTP server.  Thoughts?

**Comment by pablitoc** [comment]
There are actually patch numbers in Ruby version 2.1+ they just don't show up until you do ruby -v. so when you download them you call `2.1.2` but when you run `ruby -v` you'll get something like 2.1.2p245. True story.  

The url variable for ruby is nice but if you are not getting the url from the source how can you be sure that Ruby has not been altered in any way?  If  you are looking to pull down your own ruby versions then that person probably created their own playbook.

**Comment by pablitoc** [comment]
Also, I do not use `rolename.app_path` and/or `rolename.group/user` becaseu when they playbooks come together those variables will become redundant.  Doing it this way will still allow these playbooks to run individually and as a group.

**Comment by pjkelly** [comment]
> > The url variable for ruby is nice but if you are not getting the url from the source how can you be sure that Ruby has not been altered in any way? 

I don't think that's really your problem to worry about.  If someone wants to download a file from an untrusted source then that's their prerogative.  Since this library is open sourced, our job is to provide the simplest, most intuitive interface possible, and having those three variables that are so similar feels like a pain to me.  At the very least, you're going to need to document why/how those variables are setup that way, because it's not immediately obvious from just looking at them.

**Pull request merged**
